// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBliKsezXwZyy3BCA9XyZDC_SwY-_5ygos',
    appId: '1:1095083603413:web:cf696fe3d29247b3ab795c',
    messagingSenderId: '1095083603413',
    projectId: 'service-finder-platform-bcb35',
    authDomain: 'service-finder-platform-bcb35.firebaseapp.com',
    storageBucket: 'service-finder-platform-bcb35.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuDNk8Zoxa7KupGb4Mcf5n-RcCQBLwG60',
    appId: '1:1095083603413:android:04906d845083fcb8ab795c',
    messagingSenderId: '1095083603413',
    projectId: 'service-finder-platform-bcb35',
    storageBucket: 'service-finder-platform-bcb35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9gg3rc6R7lmqucZTra-cIyXX3u1hY3cc',
    appId: '1:1095083603413:ios:faa0a4c5ec1e38bbab795c',
    messagingSenderId: '1095083603413',
    projectId: 'service-finder-platform-bcb35',
    storageBucket: 'service-finder-platform-bcb35.firebasestorage.app',
    iosBundleId: 'com.group12.serviceFinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9gg3rc6R7lmqucZTra-cIyXX3u1hY3cc',
    appId: '1:1095083603413:ios:faa0a4c5ec1e38bbab795c',
    messagingSenderId: '1095083603413',
    projectId: 'service-finder-platform-bcb35',
    storageBucket: 'service-finder-platform-bcb35.firebasestorage.app',
    iosBundleId: 'com.group12.serviceFinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBliKsezXwZyy3BCA9XyZDC_SwY-_5ygos',
    appId: '1:1095083603413:web:3584f9bfe9bfe563ab795c',
    messagingSenderId: '1095083603413',
    projectId: 'service-finder-platform-bcb35',
    authDomain: 'service-finder-platform-bcb35.firebaseapp.com',
    storageBucket: 'service-finder-platform-bcb35.firebasestorage.app',
  );
}
