name: Flutter Mobile App Check

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          cd service_finder_app
          flutter pub get

      - name: Check for coding errors
        run: |
          cd service_finder_app
          flutter analyze

      - name: Create google-services.json
        if: github.event_name == 'push'
        run: |
          echo '${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON }}' > service_finder_app/android/app/google-services.json

      - name: Check Firebase file exists
        if: github.event_name == 'push'
        run: |
          ls -la service_finder_app/android/app/google-services.json

      - name: Build APK
        if: github.event_name == 'push'
        run: |
          cd service_finder_app
          flutter build apk --release

      - name: Upload APK
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: flutter-app-apk
          path: service_finder_app/build/app/outputs/flutter-apk/app-release.apk